page working with all the functions
Swarzstein/to-do-list pull request #3
Opened 2022-10-17 22:34 UTC by Swarzstein

## In this pull request:
- Added functions to check and set the tasks status.
- Added function to clean all the completed tasks.

2022-10-17 23:22 UTC, mirouhml requested changes
# REQUIRED CHANGES 🔴

Hi @Swarzstein, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![](https://media4.giphy.com/media/KyBesf8kNT6s88SEgb/giphy.gif?cid=ecf05e47n6s5huda7qh40syoppcaspe9vx68ddmxerd08owm&rid=giphy.gif&ct=g)

## Highlights

- Great job setting up the correct linters ✔️
- Highly organized and clean code ✔️ 👨🏻‍💻
- Professional documentation ✔️
- Correct workflow ✔️
- Meaningful commit messages ✔️

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-17 23:22 UTC, mirouhml commented on src/index.js
>              </label>
- [ ] Please know that there is an issue with this function:
  ![image](https://user-images.githubusercontent.com/20567503/196300471-06898f7e-e76b-42b9-854e-cf6201e31f51.png)
  I wasn't able to test anything, so kindly fix this issue so we can test the functionalities of your project.

2022-10-17 23:22 UTC, mirouhml commented on src/index.js
>  // Add new Task
- [ ] Please know that adding a new task isn't working at all kindly fix the issue as I wasn't able to test anything.

2022-10-17 23:22 UTC, mirouhml commented on src/index.js
>        const task = new Task();
[OPTIONAL]
- [ ] Deleting also isn't working for some reason, here is the error:
  ![image](https://user-images.githubusercontent.com/20567503/196301107-17f0a581-acde-409a-be3f-dac20df6bd64.png)

2022-10-17 23:22 UTC, mirouhml commented on src/index.js
[OPTIONAL]
- [ ] Editing also isn't working I am getting the same error as the delete error:
  ![image](https://user-images.githubusercontent.com/20567503/196301267-0eb703f8-82f4-41b4-82f2-9029cdcaf8ef.png)

2022-10-18 22:54 UTC, topeogunleye requested changes
### Hi @Swarzstein, 

# Status: Approved ✔️
Excellent job on making the changes requested by the previous code reviewer. Keep it up 👏

Your project is complete! There is nothing else to say other than... it's time to merge it 💪
Congratulations! 🎉
![congratulations](https://user-images.githubusercontent.com/52934128/163691476-087b4b9c-825b-40a3-85a1-d1bde44ffa53.gif)
>
## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Followed Github flow :heavy_check_mark:
- Professional README file. :heavy_check_mark:
- PR has a good title and description :heavy_check_mark:
 
## [Optional] suggestions:
* Ntohing to mention.
 
 _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
 
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.



------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-18 23:26 UTC, merged